# Generated by Django 5.2.4 on 2025-08-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='manager',
        ),
    ]
