# Generated by Django 5.2.4 on 2025-08-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_options_remove_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'ordering': ['warehouse', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='parent',
        ),
    ]
