# Generated by Django 5.2.4 on 2025-08-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocklocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottracking',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='lottracking',
            name='manufacturer_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_uom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_point',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_uom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='stockmovementline',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='stockmovementline',
            name='lot_number',
        ),
        migrations.AddField(
            model_name='stockmovementline',
            name='lot_tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lottracking'),
        ),
    ]
