# Generated by Django 5.2.4 on 2025-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_lottracking_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbalance',
            old_name='quantity',
            new_name='initial_quantity',
        ),
    ]
