# Generated by Django 5.2.4 on 2025-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_quantity_to_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('semi_finished', 'Semi Finished Product'), ('finished', 'Finished Product'), ('consumable', 'Consumable'), ('spare_parts', 'Spare Parts')], default='finished', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
