# Generated by Django 5.2.4 on 2025-08-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE inventory_product DROP COLUMN IF EXISTS product_type;",
            reverse_sql="ALTER TABLE inventory_product ADD COLUMN product_type VARCHAR(50);"
        ),
    ]
