# Generated by Django 5.2.4 on 2025-08-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_type_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE inventory_product DROP COLUMN IF EXISTS reorder_point;",
            reverse_sql="ALTER TABLE inventory_product ADD COLUMN reorder_point DECIMAL(15,3);"
        ),
    ] 