# Generated by Django 5.2.4 on 2025-08-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_reorder_point_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE inventory_product DROP COLUMN IF EXISTS purchase_price;",
            reverse_sql="ALTER TABLE inventory_product ADD COLUMN purchase_price DECIMAL(15,2);"
        ),
    ] 