# Generated by Django 5.2.4 on 2025-08-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_purchase_price_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE inventory_product DROP COLUMN IF EXISTS sale_price;",
            reverse_sql="ALTER TABLE inventory_product ADD COLUMN sale_price DECIMAL(15,2);"
        ),
    ] 